### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by TC30532** [TC30532/furima-30532#9]
#URL
https://furima-30532.herokuapp.com/

#Basic認証のIDとパスワード 
ID: partneradmin
Pass: apple123

#出品者用のメールアドレスとパスワード
ID: visitor123@abc.com
Pass: apple123

#購入者用のメールアドレスとパスワード
ID: visitor456@abc.com
Pass: apple123

#購入用カードの番号・期限・セキュリティコード
カード番号: 4242424242424242
有効期限(MM/YY): 12/23
CVC: 123

よろしくお願いいたします。

**Comment by mutorisa** [comment]
堀内さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、修正していただきたい項目がございましたので、以下のご確認をお願いします！

**[修正依頼項目]**

- [ ] basic認証が実装されている
**→現状、実装されていない状態の為、実装しましょう！**

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A
※新しいissueを作っていただく必要はありません

**Comment by TC30532** [comment]
お疲れさまです！ご確認ありがとうございます！
GitHubへの反映手順に問題があったようでして、basic認証設定前の状態に戻ってしまっておりました。
ご指摘いただきありがとうございます。
basic認証再実装いたしましたので、お手数をおかけいたしますが、ご確認のほどよろしくお願いいたします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
